### ISSUE TITLE
Subordinate include files are not staged up to compute node

### ISSUE THREAD

**Issue by niklasmelin** [erik78se/Jobbers#29]
**Severity: Critical:** 

Example:
job.inp
    includefile_1.inc
          include_2.inc
          include_3.inc

Currently include_2.inc and include_3.inc are not added to the list of files to be staged up on the compute node.  Only include_file1.inc will be added.

An example model is available on: well-moray.maas.rnd.scania.com
Path: /scratch/debug/
Model: cylinder.inp

**Comment by erik78se** [comment]
seems legit

**Comment by hallback** [comment]
I think I might have fixed it by adding recursion in files_to_stage(), see commit 4e1fcc2daecddafdb8e2659aa3e89fcdb14e15aa

**Comment by hallback** [comment]
I think I might have fixed it by adding recursion in files_to_stage(), see commit 4e1fcc2daecddafdb8e2659aa3e89fcdb14e15aa

**Comment by hallback** [comment]
Commit 44e1ffcc2 solves the problem with the current test cases we've been using.
